name: iautomat_core_datasource
description: Core datasource infrastructure for enterprise Flutter applications
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0

  # REST
  dio: ^5.0.0
  retrofit: ^4.0.0

  # Utils
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  freezed: ^2.5.0
  mockito: ^5.4.0
  fake_cloud_firestore: ^3.0.0